CLDR-14399 move to OpenLiberty, add API server
- deployment is now different, but the github action has been updated
- for local dev: see cldr-apps/README.md

diff --git a/tools/scripts/ansible/templates/deploy-sh.j2 b/tools/scripts/ansible/templates/deploy-sh.j2
--- a/tools/scripts/ansible/templates/deploy-sh.j2
+++ b/tools/scripts/ansible/templates/deploy-sh.j2
@@ -4,9 +4,9 @@
 GITHUB_SHA=$1
 UNLOCK=$2
 WORKDIR=${TMPDIR-/tmp} # keep all random files here
-export TPASS={{ surveytooldeploy.password }} # from surveytooldeploy.password
-export TUSER=surveytooldeploy # fixed for now
+SERVICE="{{ cldr_openliberty_service }}"
 
+# TODO: "dogit" could be split out as a separate script
 dogit() {
     rm -f ${WORKDIR}/git-list.txt
     if [[ ${GITHUB_SHA} = "master" ]];
@@ -51,14 +51,33 @@ dogit() {
 
 # Check git first, before undeploying. Want to exit early
 (cd  {{ cldr_trunk_path }} && dogit ) || exit 1
-# undeploy old ST
-curl -u ${TUSER}:${TPASS} 'http://localhost:8080/manager/text/undeploy?path=/cldr-apps'
-# reset last deploy status
-rm -fv ${WORKDIR}/cldr-apps.war ${WORKDIR}/deploystatus
-# copy cldr-apps.war from action runner to server
-dd bs=1024000 status=progress of=${WORKDIR}/cldr-apps.war
+# 
+# stop server
+sudo -u root /usr/sbin/service ${SERVICE} stop
+# clear cache
+if [[ -d /srv/st/config/.cache ]];
+then
+   echo "Deleting cache /srv/config/.cache"
+   rm -rf /srv/st/config/.cache
+fi
+rm -fv ${WORKDIR}/cldr-apps.zip ${WORKDIR}/deploystatus
+# copy cldr-apps.zip from action runner to server
+dd bs=1024000 status=progress of=${WORKDIR}/cldr-apps.zip
 # this counts the # of files to make sure it's not too short, but also verifies that unzip is OK
-echo ; echo -n 'Unzip check, # of files in cldr-apps.war: '
-(unzip -l ${WORKDIR}/cldr-apps.war | wc -l ) || exit 1
+echo ; echo -n 'Unzip check, # of files in cldr-apps.zip: '
+(unzip -l ${WORKDIR}/cldr-apps.zip | wc -l ) || exit 1
+cd ${WORKDIR} || exit 1
+rm -rf ./deploy || exit 1
+mkdir ./deploy
+cd ./deploy
+unzip ${WORKDIR}/cldr-apps.zip
+if [[ ! -d ./wlp ]];
+then
+    echo "Error, did not get a ./wlp dir from this zip.. stop"
+    exit 1
+fi
 # Now, do the deployment!
-curl -q -u ${TUSER}:${TPASS} 'http://localhost:8080/manager/text/deploy?path=/cldr-apps&tag=cldr-apps&update=true' -T ${WORKDIR}/cldr-apps.war | tee ${WORKDIR}/deploystatus
+# exclude these two files
+rsync -r --exclude server.env --exclude workarea --exclude bootstrap.properties -v \
+      --delete ./wlp/usr/servers/cldr/* /var/lib/openliberty/usr/servers/cldr/ || exit 1
+sudo -u root /usr/sbin/service ${SERVICE} start || exit 1
