CLDR-15990 Generate .xsd and .md from .dtd (#3108)
* CLDR-15990 Generate .xsd from .dtd

- originally #2350
- also creates .md files from the .dtd for aid in spec updating

(cherry picked from commit cb6c8bf4928bd219e49620e355f11c67df360e34)
(cherry picked from commit 4fd3cef8f67bc2fd1df0fe17b66dd4f772b377ca)

Co-authored-by: Marc Durdin <marc@durdin.net>

* CLDR-15990 checkin initial .xsd

- also add test in workflow (test is advisory. does not fail)
- ignore xml.xsd as it is not usefulx

* CLDR-15990 cleanup xsd and dtd2md code

- separated the markdown and xsd generation
- cleaned up paths and output

* CLDR-15990 remove @-annotations from .xsd

---------

Co-authored-by: Marc Durdin <marc@durdin.net>

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -119,6 +119,13 @@ jobs:
           -Dexec.cleanupDaemonThreads=false
           -Dexec.args="-q --justCheckBom exemplars seed common keyboards"
           && echo 'No XML BOM detected'
+      - name: Schema check common/main in .xml files
+        run: >
+          mvn -s .github/workflows/mvn-settings.xml --file tools/pom.xml -pl cldr-code
+          exec:java -Dexec.mainClass=org.unicode.cldr.util.XMLValidator
+          -Dexec.cleanupDaemonThreads=false
+          -Dexec.args="-q --schema=common/dtd/ldml.xsd  common/main"
+          || (echo 'Schema failed, rerun GenerateDtd' ; exit 0)
       - name: Setup MySQL
         run: |
           sudo systemctl start mysql.service
